services:
  db:
    image: mitgar14/mysql-airbnbs
    ports:
      - 3316:3306
  usuarios:
    image: mitgar14/usuarios
    depends_on:
      - db
    ports:
      - 3001:3001
  airbnbs:
    image: mitgar14/airbnbs
    depends_on:
      - db
    ports:
      - 3002:3002    
  reservas:
    image: mitgar14/reservas
    depends_on:
      - db
    ports:
      - 3003:3003
  web1:
    image: mitgar14/web-airbnbs
    depends_on:
      - usuarios
      - airbnbs
      - reservas
  web2:
    image: mitgar14/web-airbnbs
    depends_on:
      - usuarios
      - airbnbs
      - reservas
  haproxy:
    image: mitgar14/haproxy-airbnbs
    depends_on:
      - web1
      - web2
    ports:
      - "5080:80"
  transferencia_df:
    image: mitgar14/transferencia_df-airbnbs
    depends_on:
      - db
networks:
  airbnbs_platform:
