services:
  db:
    image: mitgar14/mysql-airbnbs
    ports:
      - 3316:3306
    deploy:
      placement:
        constraints:
          - node.hostname == serverAirbnb
  usuarios:
    image: mitgar14/usuarios
    depends_on:
      - db
    ports:
      - 3001:3001
    deploy:
      placement:
        constraints:
          - node.hostname == serverAirbnb
  airbnbs:
    image: mitgar14/airbnbs
    depends_on:
      - db
    ports:
      - 3002:3002
    deploy:
      placement:
        constraints:
          - node.hostname == serverAirbnb
  reservas:
    image: mitgar14/reservas
    depends_on:
      - db
    ports:
      - 3003:3003
    deploy:
      placement:
        constraints:
          - node.hostname == serverAirbnb
  web1:
    image: mitgar14/web-airbnbs
    depends_on:
      - usuarios
      - airbnbs
      - reservas
    deploy:
      placement:
        constraints:
          - node.hostname == workerAirbnb
  web2:
    image: mitgar14/web-airbnbs
    depends_on:
      - usuarios
      - airbnbs
      - reservas
    deploy:
      placement:
        constraints:
          - node.hostname == workerAirbnb
  haproxy:
    image: mitgar14/haproxy-airbnbs
    depends_on:
      - web1
      - web2
    ports:
      - "5080:80"
    deploy:
      placement:
        constraints:
          - node.hostname == serverAirbnb
  transferencia_df:
    image: mitgar14/transferencia_df-airbnbs
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.hostname == workerAirbnb
networks:
  airbnbs_platform:
