services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=airbnb_app
    ports:
      - 3316:3306
    expose:
      - 3316
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  transferencia_df:
    build: ./transferencia_df
    depends_on:
      - db

  usuarios:
    build: ./microservicios/usuarios
    depends_on:
      - db
    ports:
      - 3001:3001

  airbnbs:
    build: ./microservicios/airbnbs
    depends_on:
      - db
    ports:
      - 3002:3002
      
  reservas:
    build: ./microservicios/reservas
    depends_on:
      - db
    ports:
      - 3003:3003

  web:
    build: ./web
    depends_on:
      - usuarios
      - airbnbs
      - reservas
    ports:
      - 3000:3000
networks:
  airbnbs_platform: